name: CI Pipeline - Dev

on:
  push:
    branches:
      - dev

jobs:
  dev:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run test-dev Update
        run: |
          sudo su - egap -c '~/.local/bin/odoo-update dev --force'
