name: Deploy em Produção

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Atualizar código e rodar Odoo
        run: |
          cd /opt/odoo/custom/
          git pull origin main
          cd ..
          source .venv/bin/activate
          odoo-bin -u all
