jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Atualizar e reiniciar Odoo
        run: |
          cd /opt/odoo/custom/
          git pull origin main
          source /opt/odoo/.venv/bin/activate
          /opt/odoo/odoo-bin -c  --max-cron-threads=0 --no-http --stop-after-init -u all

