name: CI Pipeline - Main (Manual)

on:
  workflow_dispatch:

jobs:
  test-main:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run test-dev Update
        run: |
          sudo su - egap -c '~/.local/bin/odoo-update odoo --force'
