name: CI Pipeline

on:
  # Automatically run on pushes to test-dev
  push:
    branches:
      - dev

  # Adds a “Run workflow” button for manual execution
  workflow_dispatch:

jobs:
  dev:
    # Only runs on push events to test-dev
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/test-dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run test-dev Update
        run: |
          sudo su - egap -c '~/.local/bin/odoo-update dev'

  main:
    # Only runs when manually triggered on test-main
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    #needs: test-dev    # optional: skip or wait for test-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run main Tasks
        run: |
          echo "Executing on the test-main branch"
