name: Deploy Pre-Main

on:
  push:
    tags:
      - 'prod-*'

jobs:
  deploy-pre-main:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run pre-main Update
        run: |
          sudo su - egap -c '~/.local/bin/odoo-update odoo --force'
